server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-vue?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&serverTimezone=GMT%2b8
    username: Bruce
    password: 123456
#    日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# 支付宝的配置
# appId
alipay.appId: 2021000122688155
# 应用私钥
alipay.appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCgpf3N4Hswzm0GIj0wYGc+dhYf8UqLzAaBp4mtPwhJFAsVDWqhFEQ3fTi0ZCsQIdKhwM9yf6kyT04Pnun5swL8NL9XIwz5lSvlbwi9jb1hJAMJhRMJEc4wdcrm8yDQfgpUWtcg7E/lLPR1ZcPtlE6BEnOZi5QHXpufm/IkLpCVlCAZrNCnOYlWx2olU7HiObtlmPq1Spkx/bOUY8iAdm7M6fk7Q87OopFIORcrZZDg4ATyknS9HIefv0/TfMNyNm+u6AhXT2UcksX0QJ1s4tMmOphaumsC8ZPPkmVTSl4bSHj5w4/rfQlvDVK/ywFd8/5iiHeaGdHyDayP13QXXJCfAgMBAAECggEBAIBoLZaB9/XrCfn9JCum4t9qRAUEOTHEwu6fm8x+tYC0JKePMcvPBzfTP5/w8PrUDih8lVRP9k3gVeTmgN61140AHHDp81ULhyq8tZ/Ny7H5tvPFCpIVSVoyzRwM+g2ssVT7xzjpqnLknAG6dgFQqe9BcGUqzAeX94x8ee+xyJ/FnyiJCZu5uJ4ftd73XSeaqUjdUwu9YY/e2fYFWJV47I7iXtZaoF/ggzcWU28hYjkrueRH2XvJ54uoYQmX8Q/xKgpLOFC9LoRx3feipwszy3lYNetJ2ub2eDAZE7a8Cd2Uk+CssOOPa9Q9U3/6/5kIhsufTWY8hDqpTZx7Q2Nr4QECgYEA6H68dokVZGAP9UVkbb9SKfnb9uto7KgUyYKVYuYJcpcJDBf/n+XG8s50xKwV9UdAfnbnK9/61DCeWsMZewkciaz0QP4tsFCVbekfpqp/rYK//Dq+2NFPGU7qHoxELq54I0HzS2487Ohlo22HASert/dGDBNEuwahS9cgUpU5qQMCgYEAsOPGCi6zmuq2a6eSZKtPoxMxYls87+ATPwpNny1/RawwJVCmR/U1NjV1dBfW84OpSMoqR3BFpyF8ESAPfMKytvVWcatw1wlyTp0wI7rn9li1pfXCnf8xuuaI+yq4TaNmOK7lmzPnrfHjssZjR5Tazq/hzx2xshhlTNUiQRqxMTUCgYEArsFcjci6oKkoNZdERs3xR4X81dvbEU/B2DnkaeM5JL3sWf/L7/d6FFYlJROoqaY2Dxj26F7CHi6xSM2vYHDX15B+REAKPaZEu8noNZGgyN4nysKpYzXpO7+6cN3D/ka8HNxcsM0a1IRWqYIRYUfdZjlimH7/QYlZQjVgoVJzddsCgYAVkjE8XKWaZrUIO88mZ522jUigbe/ocLLoJSGCH9I9dNoKMuOUMtriWXKRTbbwy0WBkuXFAHP+BZ9Tl01MMZIJrbF0+ysvjf9ahuCv+sL+z6KXMnkhO1WdLS/XMUZ4cUyt7OYjHxlJpQ3XZ0oEGKr2OYyX7U8WINN5oyQiPFcPYQKBgEkYMzcPHbB/KDuvpA+iTLsgpxHK80idYrQHRwiaokuTLxSTDQmWVJB61H4zX0NkiERU0lqSGUIAjvh/EFOEYK/6N9gofHHuvKWd6kPUZFKIz8FJvkKb0ASHuJT5DwDsPOyOWwWBvU+sUmjLNbQxgpAAkNmty2NW+VUtvhrML7G1
# 支付宝公钥
alipay.alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhXu9nfW32ajp6Ck4xPvfLOJ9JggCaN3VOjUMwNDsn8MyX/W6F4S+7e/Tv9Px1WPHOgKUzUvmgzFbV8SzsdI/exQEyWUik7mXda0vzAZo7LG3ioh95C4Vt3Lt82Qp+S3jL1wEo03iWEuilSNQjsoqbR2kLjNrF3YkAsH597SXPd+1I4zi+z9J9JAPoKPNg0GxdrIKieVBi5jWW/EQbU/7DpgZn/5h2n3iGSWtryY0fJaetKrUtUCBZWFSTKlPsM4ab0WHoMXNqFq+hQsV+3Tat3MexAc2tiTVk12QGS2qBMnSZqYX6+COStLC4O/MhlrHBnfCdbw4Omk9idWKZGhK9wIDAQAB
# 支付成功回调地址
alipay.notifyUrl:    http://zhnva8.natappfree.cc/alipay/notify

# 卖家账号
#  pvrktn5227@sandbox.com